### ISSUE TITLE
AttributeError: AdvA

### ISSUE THREAD

**Issue by yangte** [Matheus-Garbelini/sweyntooth_bluetooth_low_energy_attacks#35]
Hi  ,all 
Traceback (most recent call last):
  File "Telink_zero_ltk_installation.py", line 234, in <module>
    if (BTLE_SCAN_RSP in pkt or BTLE_ADV in pkt) and pkt.AdvA == advertiser_address.lower() and connecting == False:
  File "/home/janlice/sweyntooth/sweyntooth_bluetooth_low_energy_attacks/libs/scapy/packet.py", line 368, in __getattr__
    return self.payload.__getattr__(attr)
  File "/home/janlice/sweyntooth/sweyntooth_bluetooth_low_energy_attacks/libs/scapy/packet.py", line 368, in __getattr__
    return self.payload.__getattr__(attr)
  File "/home/janlice/sweyntooth/sweyntooth_bluetooth_low_energy_attacks/libs/scapy/packet.py", line 368, in __getattr__
    return self.payload.__getattr__(attr)
  File "/home/janlice/sweyntooth/sweyntooth_bluetooth_low_energy_attacks/libs/scapy/packet.py", line 366, in __getattr__
    fld, v = self.getfield_and_val(attr)
  File "/home/janlice/sweyntooth/sweyntooth_bluetooth_low_energy_attacks/libs/scapy/packet.py", line 1585, in getfield_and_val
    raise AttributeError(attr)
AttributeError: AdvA
I have faced a question ,when I do Telink_zero_ltk_installation.py, I found always have AttributeError: AdvA , Does anyone know what's going on?

**Comment by Elnatan-lazar** [comment]
hi did you figure this out? i having the issues 

> Hi ,all Traceback (most recent call last): File "Telink_zero_ltk_installation.py", line 234, in if (BTLE_SCAN_RSP in pkt or BTLE_ADV in pkt) and pkt.AdvA == advertiser_address.lower() and connecting == False: File "/home/janlice/sweyntooth/sweyntooth_bluetooth_low_energy_attacks/libs/scapy/packet.py", line 368, in **getattr** return self.payload.**getattr**(attr) File "/home/janlice/sweyntooth/sweyntooth_bluetooth_low_energy_attacks/libs/scapy/packet.py", line 368, in **getattr** return self.payload.**getattr**(attr) File "/home/janlice/sweyntooth/sweyntooth_bluetooth_low_energy_attacks/libs/scapy/packet.py", line 368, in **getattr** return self.payload.**getattr**(attr) File "/home/janlice/sweyntooth/sweyntooth_bluetooth_low_energy_attacks/libs/scapy/packet.py", line 366, in **getattr** fld, v = self.getfield_and_val(attr) File "/home/janlice/sweyntooth/sweyntooth_bluetooth_low_energy_attacks/libs/scapy/packet.py", line 1585, in getfield_and_val raise AttributeError(attr) AttributeError: AdvA I have faced a question ,when I do Telink_zero_ltk_installation.py, I found always have AttributeError: AdvA , Does anyone know what's going on?
